require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
AllCops:
    NewCops: enable

Style/Documentation:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 3
